version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html

hooks:
  - location: DeploymentGroup
    timeout: 3
    runas: root
    script:
      - echo "Executing a script during the deployment to BackendDeployment group."

  - location: AfterInstall
    timeout: 3
    runas: root
    script:
      - echo "Executing a script after installing the new version."

  - location: ApplicationStop
    timeout: 6
    runas: root
    script:
      - echo "Executing a script to stop the application before deployment."

  - location: ValidateService
    timeout: 3
    runas: root
    script:
      - echo "Executing a script to validate the service after deployment."

  - location: ApplicationStart
    timeout: 6
    runas: root
    script:
      - echo "Executing a script to start the application after deployment."
